# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cine SKY' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cine SKY

    pod "TinyConstraints"
  	pod "Alamofire"
    pod 'SwiftyJSON'

end
